[package]
name = "bevy_rapier_collider_gen"
# don't manually edit this version unless you're sure you want to circumvent the process documented in RELEASE.md
version = "0.4.1"
edition = "2021"
homepage = "https://github.com/shnewto/bevy_rapier_collider_gen"
license = "MIT OR Apache-2.0"
repository = "https://github.com/shnewto/bevy_rapier_collider_gen"

description = "a library for generating bevy_rapier2d colliders, for bevy apps, from images with transparency"
keywords = ["bevy", "rapier", "png", "collider", "2d"]
readme = "README.md"

[dependencies]
bevy = "0.13.0"
bevy_rapier2d = "0.25.0"

[dev-dependencies]
bevy_prototype_lyon = "0.11.0"
indoc = "2.0.4"

[[example]]
name = "colliders"
path = "examples/colliders.rs"
